# Generated by Django 5.2.8 on 2025-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_honeyguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeyguardlog',
            name='accept_encoding',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Accept Encoding'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='accept_language',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Accept Language'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='elapsed_time',
            field=models.FloatField(blank=True, help_text='Time in seconds between form render and submission', null=True, verbose_name='Elapsed Time'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='honeypot_triggered',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the honeypot field was filled', verbose_name='Honeypot Triggered'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, help_text='IP address of the requester', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10, verbose_name='Request Method'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password submitted in login attempt', max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='path',
            field=models.CharField(db_index=True, help_text='URL path accessed', max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='raw_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Raw request metadata for debugging', verbose_name='Raw Metadata'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='referer',
            field=models.CharField(blank=True, default='', help_text='HTTP referer header', max_length=500, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='timing_issue',
            field=models.CharField(choices=[('too_fast', 'Too Fast'), ('too_slow', 'Too Slow'), ('valid', 'Valid Timing')], default='valid', help_text='Type of timing anomaly detected', max_length=20, verbose_name='Timing Issue'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent string from request', verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='honeyguardlog',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Username submitted in login attempt', max_length=255, verbose_name='Username'),
        ),
    ]
